### ISSUE TITLE
SBSA timer t007_entry

### ISSUE THREAD

**Issue by tingwanyang** [ARM-software/sbsa-acs#104]
HI,

I have a question about timer t007_entry. In test_pool/timer_wd/test_t007.c Line 85,  cnt_base_n + 0x0 register is 64-bit, But val_mmio_read function only read 32-bit, In hardware, 64-bit need 64-bit read. May I know the reason?

Many thanks
Tingwan

https://github.com/ARM-software/sbsa-acs/blob/1f8fb3105d709da245a0ec9442d4ea7a34218e33/test_pool/timer_wd/test_t007.c#L85

**Comment by gowthamsiddarthd** [comment]
Hi Tingwanyang,

As per the[ SBSA specification](https://developer.arm.com/documentation/den0029/d/?lang=en) section 3.1.7.4 provides the summary of the CNTBaseN frame register.
Here we check the read-only aspect of the register CNTPCT[31:0] and any writes to this read-only register should be ignored. Even though the physical count register is two 32-bit registers and since we do not verify the value of the register (we verify only the RO property), it suffices to just check the 31:0 bit value of the CNTPCT register.

Regards,
Gowtham

-- Enterprise ACS Support
