### ISSUE TITLE
Exerciser Sbsa compliance is only from Level 4

### ISSUE THREAD

**Issue by hrw** [ARM-software/sbsa-acs#320]
When SBSA ACS is run for level 3 there is an info about exerciser tests:

```
      *** Starting PCIe Exerciser tests ***
Exerciser Sbsa compliance is only from Level 4
```

Shouldn't whole block be skipped?

**Comment by chetan-rathore** [comment]
Hi @hrw, 

We are working on the changes and expected to be upstreamed by this week.
Please note the proposed changes.

- Exerciser test 1 which does sanity testing will run at Level 3..so that any system which has exerciser...a basic sanity is done at the starting level.
- Then as per specification, the exerciser test will run at L6 and L7 based on a rule which is covered by the test.

Thanks,
ACS team
